floriansaqipi/tic_tac_toe_minimax_multiplayer

app.js, package-lock.json, package.json, routes/player.js, views/test.html
In this task, I have added the basic code structure for a Node.js app. I have set up the server, used the nodemon package to add some scripts to run the server and refresh automatically. I have added the express package and have set up the basic routes using its router and added  a request handler for undefined request locations (404). Also I have defined the views directory.
=> [TTTMA-2] - adding basic code structure

index.html, style.css
Html and css:
- Enlarged the game grid for a more immersive gaming experience.
- Increased the size of X and O symbols to improve visibility.
- Repositioned the "Play Again" and "Go Back" buttons for better accessibility.
- Improved overall styling for a polished and attractive game interface.
=> [TTTMA-12] - add- tic-tac-toe-page-design

script.js
JS
Enabled players to place 'X' or 'O' on the board by clicking.
Added game logic for turn switching, win, and draw detection.
Reset functionality for replaying the game.
=> [TTTMA-13] - add-ability-to-place- something-on-the-board-via-click-event

index_landing.html, landing.js, style_landing.css
HTML / CSS / JS
Modernized radio buttons and dropdown for improved interactivity.
Enhanced responsive design for better cross-device compatibility.
Updated UI with new color scheme and subtle animations.
Added smooth navigation links between landing and game pages.
=> [TTTMA-11] - add-landing-page

index.html, index_landing.html, style.css
I wrapped the Tic Tac Toe landing page in a <form> to allow for data submission.
Then, I have added form elements to capture user choices (symbol and who plays first),
So at the end I modified the button to be of type "submit" for form submission.
=> [TTTMA-22] - fix-wrapping-form-around-the-landing-page

routes/player.js
The function for handling the landing page
=> [TTTMA-20]-Handle-the-landing-page-POST-request

public/js/script.js, routes/player.js, views/index.ejs, views/index_landing.ejs
Fixed the bug that didn't allowed to pass data objects
=> [ TTTMA-31 ] - fix-the-fetching-of-the-isPc-and-turn-variables

views/index_landing.ejs
X radio button is selected by default
=> [TTTMA-32]-x-radio-button-should-be-selected-by-default

public/css/style.css, public/js/landing.js, public/js/script.js, views/index.ejs
In this task, the objective was to enhance the user experience by displaying the player's name on the game page. The player enters their name on the landing page, and the name is then passed to the game page. This was achieved by utilizing client-side JavaScript to store the player's name in local storage upon submission of the landing page form. On the game page, the script retrieves the player's name from local storage, ensuring a personalized and engaging gaming experience.
=> [TTTMA - 36] - display-username-in-the-game-page

public/js/script1.js, routes/player.js, views/index.ejs
This is the updated version of javascript file where the minmax algorithm and static board state will be implemented
=> [ TTTMA-37 ] - Update-the-script-file-logic

public/js/script1.js
There is the implementation of the static board evaluation function.
=> [ TTTMA-26 ] - Configure-a-static-evaluation-function-of-the-board-state

public/js/script1.js
This part of the code implements minimax algorithm
=> [ TTTMA-27 ] - implement-the-minimax-algorithm

package-lock.json, package.json, public/css/index.css, routes/player.js, views/index.ejs
I incorporated some server side validation using the express-validator package.
=> [ TTTMA-45] - handle validation on name input form

public/css/404.css, public/css/index.css
I changed the style of input name form and the background-color of 404 page.
=> [TTTMA-38]-update-the-input-name-form

public/js/board.js
This is the implementation of the Alfa-Beta pruning in the minimax algorithm
=> [ TTTMA-28 ] - Add-alfa-beta-pruning-to-the-algorithm

app.js, public/js/board.js, views/board.ejs
TTTMA-47-Add-a-basic-socket-connection
=> [ TTTMA-47 ] - Add a basic socket connection

controllers/player.js, routes/player.js
I removed the double checks on validation since they were being done both in the controller and in the route, which shouldn't be the case.
=> [ TTTMA-58 ] - removed unnecessary double checks

algorithm/minmax.js, app.js, public/js/board.js
Implement private room between client and server
=> [ TTTMA-53 ] -  Implement private room between client and server

public/css/board.css, public/js/board.js
In this code i fixed the switching turn design and added some structure in the code.
=> [ TTTMA-60 ] - Fix-the-switching-turn-design-bug

public/css/board.css, views/board.ejs
the task to fix the go back and play again buttons is accomplished!
=> [TTTMA-66]-fix-the-go-back-and-play-again-buttons

public/css/index.css
=> [TTTMA-65]-fix-the-name-input

public/css/board.css
The design of the text that is shown after the end of the game is improved!
=> [TTTMA-64]-improve-design-in-case-of-win-or-loss

public/js/board.js
The player is able to click once when it is its turn
=> [TTTMA-67]-fix-the-clicking-fast-issue

public/css/board.css, public/css/index.css, views/board.ejs, views/index.ejs
The game is now compatible in all devices!
=> [TTTMA-63]-fix-responsiveness-of-the-page
